name: dld
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  camera: ^0.10.3
  json_annotation: ^4.1.0
  dotted_border: ^2.0.0+1
  dio: ^5.0.0
  get: ^4.6.5
  intl: ^0.19.0
  flutter_svg: ^2.0.1
  shared_preferences: ^2.0.17
  package_info_plus: ^8.1.2
  fluttertoast: ^8.0.8
  cached_network_image: ^3.2.0
  url_launcher: ^6.1.5
  image_picker: ^0.8.4+4
  device_preview: ^1.1.0
  flutter_html: ^3.0.0-beta.1
  lazy_load_indexed_stack: ^0.1.4
  google_fonts: ^4.0.3
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^18.0.1
  flutter_cached_pdfview: ^0.4.1
  add_2_calendar: ^3.0.1
  carousel_slider: ^5.0.0
  #Permission
  permission_handler: ^10.2.0
  path_provider: ^2.0.13
  pin_code_fields: ^8.0.1
  win32: ^5.0.0
  #UUID
  uuid: ^4.3.3
  #QR
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.6
  #deviceinfo
  device_info_plus: ^11.2.1
  jwt_decode: ^0.3.1
  connectivity_plus: ^5.0.2
  flutter_udid: ^3.0.0
  webview_flutter: ^4.4.2
  #Firebase
  firebase_core: ^2.2.0
  firebase_analytics: ^10.0.5
  #location
  google_maps_flutter: ^2.10.0
  flutter_polyline_points: ^2.1.0
  location: ^7.0.1
  geocoding: ^3.0.0
  fl_chart: ^0.70.0
  skeletonizer: ^1.4.3
  shimmer: ^3.0.0
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
  adaptive_icon_background: "#00FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"
